version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=SocialAPI;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - Jwt__Key=your-super-secret-key-with-at-least-32-characters
      - Jwt__Issuer=http://localhost:5000
      - Jwt__Audience=http://localhost:5000

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd 